version: '3.5'

services:
  kafka-connector-loader:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    environment:
      - CONNECT_SERVICE_NAME
    networks:
      - kafka-net
    volumes:
      - connect-jars-vol:/connect-jars
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.1'
          memory: 64M
        reservations:
          memory: 52M

networks:
  kafka-net:
    name: ${KAFKA_NET_NAME:-kafka-net}
    external: true
