version: '3.5'

services:
  kafka-connector-loader:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    command: cp /jar/* /connect-jars
    networks:
      - kafka-net
    volumes:
      - connect-jars-vol:/connect-jars
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none
      resources:
        limits:
          cpus: '0.1'
          memory: 64M
        reservations:
          memory: 52M

networks:
  kafka-net:
    name: ${KAFKA_NET_NAME:-kafka-net}
    external: true

volumes:
  connect-jars-vol:
    name: ${CONNECT_JARS_VOL_NAME:-connect-jars-vol}
